[package]
name = "bevy_water"
version = "0.10.1"
edition = "2021"
authors = ["Robert G. Jakabosky <rjakabosky+neopallium@neoawareness.com>"]
license = "MIT/Apache-2.0"
description = "Dynamic ocean material for Bevy."
keywords = ["water", "ocean", "waves", "bevy"]
repository = "https://github.com/Neopallium/bevy_water"
homepage = "https://github.com/Neopallium/bevy_water"

[dependencies]
anyhow = "1.0"

bevy = { version = "0.10", default-features = false, features = ["bevy_asset", "bevy_render", "bevy_pbr"] }

[dev-dependencies]
bevy = "0.10"
bevy_atmosphere = { version = "0.6" }
bevy_spectator = "0.2"
