[package]
name = "bevy_water"
version = "0.11.0"
edition = "2021"
authors = ["Robert G. Jakabosky <rjakabosky+neopallium@neoawareness.com>"]
license = "MIT/Apache-2.0"
description = "Dynamic ocean material for Bevy."
keywords = ["water", "ocean", "waves", "bevy"]
repository = "https://github.com/Neopallium/bevy_water"
homepage = "https://github.com/Neopallium/bevy_water"

[patch.crates-io]
bevy = { git = "https://github.com/bevyengine/bevy.git", branch = "main" }

[features]
default = ["webgl2", "embed_shaders", "depth_prepass"]

# Embed the shaders at compile-time.
embed_shaders = []

# Enable debug lines in examples.
debug = []

# Enable bevy_atmosphere support.
atmosphere = []

# Enable DepthPrepass in examples.
depth_prepass = []

# Select WebGL2 or WebGPU support.
# Use webgl2 for native builds (non-wasm).
webgl2 = [ "bevy_common", "bevy/webgl2" ]
webgpu = [ "bevy_common" ]

# All common bevy features.
bevy_common = [
  "bevy/animation",
  "bevy/bevy_asset",
  "bevy/bevy_audio",
  "bevy/bevy_gilrs",
  "bevy/bevy_scene",
  "bevy/bevy_winit",
  "bevy/bevy_core_pipeline",
  "bevy/bevy_pbr",
  "bevy/bevy_gltf",
  "bevy/bevy_render",
  "bevy/bevy_sprite",
  "bevy/bevy_text",
  "bevy/bevy_ui",
  "bevy/png",
  "bevy/hdr",
  "bevy/ktx2",
  "bevy/zstd",
  "bevy/vorbis",
  "bevy/x11",
  "bevy/filesystem_watcher",
  "bevy/bevy_gizmos",
  "bevy/android_shared_stdcxx",
  "bevy/tonemapping_luts",
  "bevy/default_font",
]

[dependencies]
anyhow = "1.0"

bevy = { version = "0.11.0", default-features = false, features = ["bevy_asset", "bevy_render", "bevy_pbr"] }

[dev-dependencies]
bevy = { version = "0.11.0", default-features = false } 
#bevy-inspector-egui = { version = "0.18.1", optional = true }
#bevy_atmosphere = { version = "0.6", optional = true }
#bevy_prototype_debug_lines = { version = "0.10.1", features = ["3d"], optional = true }
#bevy_spectator = { version = "0.2", optional = true }
#bevy_panorbit_camera = { version = "0.4.1", features = ["bevy_egui"], optional = true }
