[package]
name = "bevy_water"
version = "0.10.4"
edition = "2021"
authors = ["Robert G. Jakabosky <rjakabosky+neopallium@neoawareness.com>"]
license = "MIT/Apache-2.0"
description = "Dynamic ocean material for Bevy."
keywords = ["water", "ocean", "waves", "bevy"]
repository = "https://github.com/Neopallium/bevy_water"
homepage = "https://github.com/Neopallium/bevy_water"

[features]
default = ["embed_shaders", "depth_prepass"]

# Embed the shaders at compile-time.
embed_shaders = []

# Enable debug lines in examples.
debug = []

# Enable DepthPrepass in examples.
depth_prepass = []

[dependencies]
anyhow = "1.0"

bevy = { version = "0.10", default-features = false, features = ["bevy_asset", "bevy_render", "bevy_pbr"] }

[dev-dependencies]
bevy = "0.10"
bevy-inspector-egui = "0.18.1"
bevy_atmosphere = { version = "0.6" }
bevy_prototype_debug_lines = { version = "0.10.1", features = ["3d"] }
bevy_spectator = "0.2"
bevy_panorbit_camera = { version = "0.4.1", features = ["bevy_egui"] }
