[package]
name = "bevy_water"
version = "0.11.0"
edition = "2021"
authors = ["Robert G. Jakabosky <rjakabosky+neopallium@neoawareness.com>"]
license = "MIT/Apache-2.0"
description = "Dynamic ocean material for Bevy."
keywords = ["water", "ocean", "waves", "bevy"]
repository = "https://github.com/Neopallium/bevy_water"
homepage = "https://github.com/Neopallium/bevy_water"

[features]
default = ["webgl2", "embed_shaders", "depth_prepass"]

# Embed the shaders at compile-time.
embed_shaders = []

# Enable debug lines in examples.
debug = []

# Enable bevy_atmosphere support.
atmosphere = []

# Enable DepthPrepass in examples.
depth_prepass = []

# Select WebGL2 or WebGPU support.
# Use webgl2 for native builds (non-wasm).
webgl2 = [ "bevy/webgl2" ]
webgpu = [ ]

[dependencies]
anyhow = "1.0"

bevy = { version = "0.11.0", default-features = false, features = ["bevy_asset", "bevy_render", "bevy_pbr"] }

[dev-dependencies]
bevy = { version = "0.11.0", default-features = false , features = [
  "animation",
  "bevy_asset",
  "bevy_audio",
  "bevy_gilrs",
  "bevy_scene",
  "bevy_winit",
  "bevy_core_pipeline",
  "bevy_pbr",
  "bevy_gltf",
  "bevy_render",
  "bevy_sprite",
  "bevy_text",
  "bevy_ui",
  "png",
  "jpeg",
  "hdr",
  "ktx2",
  "zstd",
  "vorbis",
  "x11",
  "filesystem_watcher",
  "bevy_gizmos",
  "android_shared_stdcxx",
  "tonemapping_luts",
  "default_font",
] }
bevy-inspector-egui = { version = "0.19" }
#bevy_atmosphere = { version = "0.6", optional = true }
bevy_prototype_debug_lines = { version = "0.11", features = ["3d"] }
#bevy_spectator = { version = "0.2", optional = true }
bevy_panorbit_camera = { version = "0.6", features = ["bevy_egui"] }
